#!/usr/bin/env python
# jira git pre-commit hook
# just cp to .git/hooks/commit-msg 
import sys
import re

message = open(sys.argv[-1]).read()
if not re.search(ur'[A-Z]+\-[0-9]+', message):
    print('No jira issue provided. Not commited.')
    sys.exit(1)
else:
    sys.exit(0)
